import {
  Briefcase,
  GraduationCap,
  Home,
  Mail,
  Phone,
  User,
  Linkedin,
  Github,
  Book,
  HeartHandshake,
  Building,
  Award,
  MapPin,
  Lightbulb, // Added for internships
  Sparkles, // Added for co-curricular activities
} from "lucide-react";

// NOTE: This data is now a fallback and will be replaced by data from Supabase.
// The structure is kept for reference and for pages that are not yet migrated.

export const resumeData = {
  personal: {
    name: "Sunil Khatri",
    title: "Senior Software Engineer - Automotive & Embedded Systems",
    summary:
      "Results-oriented Electrical and Electronics Engineer with 4+ years of automotive software development experience, specializing in embedded systems, AI/ML integration, and project coordination. Proven track record in leading cross-functional teams to deliver complex solutions from concept to production across major automotive OEMs including KPIT Technologies, Pravaig Dynamics, TVS Motors, and Mercedes-Benz. Expert in the full software development lifecycle (SDLC), including requirements management, system integration, validation, and agile/waterfall project management. Combines strong theoretical grounding with practical expertise in firmware development, system simulation, and workflow automation.",
    contact: {
      phone: "", // Phone number removed as requested
      email: "sunilkhatri15@gmail.com",
      location: "Ajmer, IN",
    },
    social: {
      linkedin: "https://www.linkedin.com/in/sunilk15/",
      github: "https://github.com/Sunil1234267",
    },
  },
  languages: ["English (Fluent)", "Hindi (Native)"],
  education: [
    {
      institution: "SRM Institute of Science and Technology (SRM University)",
      degree: "Bachelor of Technology (B.Tech) in Electrical & Electronics Engineering",
      location: "Chennai, TN",
      duration: "2017 - 2021",
    },
  ],
  skills: {
    "Core Embedded & Automotive": [
      "Embedded C",
      "C++",
      "Python",
      "MATLAB/Simulink",
      "TMS570",
      "STM32", 
      "ESP32",
      "Renesas",
      "Jetson Nano",
      "ARM Cortex-M",
      "Arduino",
      "FreeRTOS",
      "CAN",
      "LIN",
      "UDS",
      "MISRA C",
      "AUTOSAR",
      "ISO 26262",
    ],
    "Development & Testing Tools": [
      "Vector CANDB+",
      "CANalyzer",
      "CANoe",
      "Logic Analyzers",
      "Oscilloscopes",
      "Code Composer Studio",
      "Visual Studio Code",
      "Arduino IDE",
      "TPT (Time Partition Testing)",
      "SVN",
      "PVCS",
      "GitHub",
      "Git",
      "JIRA",
    ],
    "Modeling & Simulation": [
      "MATLAB",
      "Simulink",
      "Embedded Coder",
      "TargetLink",
      "MBSE",
      "Model-in-the-Loop (MIL)",
      "Software-in-the-Loop (SIL)",
      "V-model",
      "Agile",
      "Waterfall",
      "ANSYS Mechanical",
      "FEA",
      "LabVIEW",
    ],
    "AI/ML & Modern Technologies": [
      "n8n Workflows",
      "Agentic AI",
      "Prompt Engineering",
      "LLM Deployment",
      "Ollama",
      "Docker",
      "GPU Optimization",
      "React",
      "Vite",
      "Flask",
      "HTML/CSS",
      "JavaScript",
      "Supabase",
      "Vector Databases",
      "Raspberry Pi",
      "MQTT",
      "HTTP/REST",
      "WebSocket",
    ],
    "Advanced Specializations": [
      "Battery Management (SoC/SoH/SoE)",
      "Kalman Filters",
      "LFP Battery Systems",
      "Vehicle-level Testing",
      "Cross-functional Leadership",
      "Power BI",
      "Tableau",
      "SQL",
      "ETL Processes",
      "DevOps",
      "Nginx",
      "Cybersecurity",
      "Network Scanning",
      "PCB Layout",
      "UART",
      "SPI",
      "I²C",
    ],
  },
  experience: [
    {
      company: "KPIT Technologies",
      role: "Senior Software Engineer",
      duration: "March 2024 - August 2025",
      logo: "https://logo.clearbit.com/kpit.com",
      clients: [
        {
          name: "Mercedes-Benz",
          duration: "February 2025 - August 2025",
          logo: "https://logo.clearbit.com/mercedes-benz.com",
          responsibilities: [
            "Led SIL/MIL software testing initiatives based on project requirements using JIRA for task management and tracking.",
            "Conducted Time-Partition Testing (TPT) and Regression Testing to ensure software robustness and reliability.",
            "Managed software versions and configurations using SVN, PVCS, and GitHub.",
            "Collaborated with global teams to align testing strategies with Mercedes-Benz quality standards.",
            "Ensured compliance with automotive software quality standards and traceability requirements.",
          ],
        },
        {
          name: "TVS Motors",
          duration: "March 2024 - January 2025 (Client Location)",
          logo: "https://logo.clearbit.com/tvsmotor.com",
          responsibilities: [
            "Led end-to-end development and implementation of a new 2-wheeler feature from requirements gathering to production release.",
            "Managed system development using MATLAB/Simulink, Microsoft Visual Studio Code, Renesas microcontrollers, and ESP32.",
            "Implemented RTOS (Real-Time Operating System) for multi-threaded application execution.",
            "Ensured code compliance with MISRA C standards and successfully integrated the feature into existing CAN and LIN bus architecture.",
            "Directed validation process using debugging tools: logic analyzers, CANalyzer, and oscilloscopes.",
            "Conducted system integration testing and documented validation results for production approval.",
          ],
        },
      ],
    },
    {
      company: "Pravaig Dynamics Pvt. Ltd.",
      role: "Electronics Engineer",
      duration: "December 2021 - December 2023",
      logo: "https://logo.clearbit.com/pravaig.com",
      responsibilities: [
        "Developed embedded software for TMS570, STM32, ESP32, and Jetson Nano microcontrollers for automotive applications.",
        "Designed and implemented application software for Battery Management System (BMS), Body Control Module (BCM), and Vehicle Control Unit (VCU).",
        "Utilized Embedded C and MATLAB/Simulink for Model-Based Software Engineering (MBSE).",
        "Debugged systems using logic analyzers, CAN analyzers, and oscilloscopes.",
        "Developed CAN matrix using Vector CANDB+ and integrated individual hardware components with embedded software.",
        "Integrated and calibrated Digital Signal Processing (DSP) systems to vehicle architecture.",
        "Led a team of 2 engineers for electrification of existing ICE vehicle (software, electrical, and electronics).",
        "Applied V-model lifecycle and SDLC methodologies for development and problem-solving.",
        "Developed and implemented SoC (State of Charge), SoH (State of Health), and SoE (State of Energy) algorithms using Kalman Filters for LFP batteries.",
        "Made significant contributions to EV software architecture and electrical system design.",
      ],
    },
  ],
  internships: [
    {
      company: "RootAir Technologies Pvt. Ltd.",
      role: "Electronics and IoT Intern",
      duration: "June 2020 - September 2020",
      logo: "/path/to/rootair-logo.png",
      responsibilities: [
        "Developed IoT solutions using ESP32, Arduino, and Raspberry Pi microcontrollers.",
        "Gained expertise in sensors integration and hardware-software development lifecycle.",
        "Worked on real-time data acquisition and monitoring systems.",
        "Collaborated on embedded system design and troubleshooting.",
        "Participated in project planning and cross-functional team coordination.",
      ],
    },
    {
      company: "VETO SWITCHGEARS AND CABLES LIMITED",
      role: "Industrial Trainee",
      duration: "Jun 2019 - Jul 2019",
      logo: "https://logo.clearbit.com/vetoswitchgears.com",
      responsibilities: [
        "Assisted in the manufacturing processes for electrical components such as MCBs, cables, and switches.",
        "Participated in quality assurance and safety testing, including short-circuit analysis, to ensure compliance with consumer standards.",
      ],
    },
  ],
  projects: [
    // Professional Projects
    {
      title: "Lean Angle Sensor Implementation",
      description: "Spearheaded end-to-end development of lean angle sensor feature for TVS Apache RTR 310 motorcycle. Implemented sensor fusion techniques, conducted extensive track testing, and successfully integrated into production vehicle. Led validation through perf-board bring-up and rigorous debugging processes.",
      technologies: ["MATLAB/Simulink", "Embedded C", "CAN/LIN", "Sensor Fusion", "RTOS"],
      category: "Professional",
      duration: "March 2024 - January 2025",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Battery Management System Development",
      description: "Architected and developed comprehensive BMS software for electric vehicles at Pravaig Dynamics. Implemented advanced SoC, SoH, and SoE algorithms using Kalman Filters for LFP batteries. Ensured ISO26262 compliance and MAAB guidelines adherence.",
      technologies: ["MATLAB/Simulink", "Kalman Filters", "CAN Protocol", "ISO26262", "Embedded C"],
      category: "Professional",
      duration: "December 2021 - December 2023",
      link: "https://github.com/Sunil1234267",
    },
    
    // Academic Projects
    {
      title: "Dynamometer Data Analysis",
      description: "Conducted comprehensive analysis of dynamometer test data to evaluate engine performance characteristics. Implemented statistical methods and visualization techniques to interpret power, torque, and efficiency curves across various operating conditions.",
      technologies: ["MATLAB", "Data Analysis", "Statistical Methods", "Automotive Testing"],
      category: "Academic",
      duration: "2020-2021",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Vehicle Control Electronics System",
      description: "Designed and implemented electronic control systems for vehicle applications. Focused on sensor integration, signal processing, and real-time control algorithms for automotive applications.",
      technologies: ["Embedded C", "Microcontrollers", "Signal Processing", "Automotive Electronics"],
      category: "Academic",
      duration: "2020",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Electric Vehicle Technical Analysis Report",
      description: "Comprehensive technical analysis of electric vehicle systems including powertrain efficiency, battery management, and charging infrastructure. Evaluated performance metrics and proposed optimization strategies.",
      technologies: ["Technical Analysis", "EV Systems", "Battery Technology", "Power Electronics"],
      category: "Academic",
      duration: "2021",
      link: "https://github.com/Sunil1234267",
    },
    
    // Personal & Open-Source Projects
    {
      title: "ATS Resume Builder",
      description: "Developed an intelligent resume builder system that optimizes resumes for Applicant Tracking Systems (ATS). Features keyword optimization, formatting recommendations, and compatibility scoring to improve job application success rates.",
      technologies: ["Python", "NLP", "Machine Learning", "Web Development"],
      category: "Personal",
      duration: "2024",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Local LLM Deployment and Optimization",
      description: "Implemented and optimized local deployment of Large Language Models for enhanced privacy and reduced latency. Experimented with model quantization, inference optimization, and custom fine-tuning for domain-specific applications.",
      technologies: ["Python", "PyTorch", "Transformers", "Model Optimization", "CUDA"],
      category: "Personal",
      duration: "2024",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "AI Agent for Resume Analysis",
      description: "Developed an intelligent AI agent using N8N workflows to parse, analyze, and extract key information from resumes. Implemented skill matching algorithms and automated candidate screening processes.",
      technologies: ["N8N", "Python", "NLP", "API Integration", "Automation"],
      category: "Personal",
      duration: "2024",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Full-Stack Portfolio Website",
      description: "Built a comprehensive personal portfolio website using modern web technologies. Features responsive design, interactive components, chatbot integration, and dynamic content management.",
      technologies: ["React", "TypeScript", "Tailwind CSS", "Vite", "Supabase"],
      category: "Personal",
      duration: "2024",
      link: "https://github.com/Sunil1234267/resume_webapp",
    },
    {
      title: "Real-Time Condition Monitoring of Transformer Using IoT",
      description: "Developed a comprehensive IoT-based monitoring system for electrical transformers in smart grid applications. Implemented real-time data acquisition, cloud computing integration, and predictive maintenance algorithms to enhance grid reliability and reduce equipment failure risks.",
      technologies: ["IoT", "Cloud Computing", "Predictive Analytics", "Real-time Systems", "Smart Grid"],
      category: "Academic",
      duration: "January 2021 - May 2021",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Automatic Headlight Switcher",
      description: "Engineered an intelligent automotive safety system that automatically controls vehicle headlights based on ambient light conditions and oncoming traffic detection. Enhanced driver safety by reducing manual intervention and preventing glare-related accidents.",
      technologies: ["Arduino", "Sensors", "Automotive Electronics", "Embedded Programming"],
      category: "Personal",
      duration: "October 2019",
      link: "https://github.com/Sunil1234267",
    },
    {
      title: "Bluetooth Thermal Printer Integration",
      description: "Integrated Fronix 3\" Bluetooth thermal printer with Raspberry Pi 4 for automated receipt printing. Developed Python-based system to convert HTML receipts to ESC/POS format, created POST endpoints under Nginx, and implemented automated printing with systemd service for seamless operation.",
      technologies: ["Raspberry Pi", "Python", "ESC/POS", "Nginx", "Systemd", "Bluetooth", "Flask"],
      category: "Personal",
      duration: "2024",
    },
    {
      title: "Wireless Appliance Communicator",
      description: "Created a comprehensive IoT solution for remote control of home appliances including fans, lights, and other electrical devices. Implemented wireless communication protocols, relay control systems, and mobile interface for seamless home automation.",
      technologies: ["Arduino", "Wireless Communication", "IoT", "Relay Control", "Mobile App"],
      category: "Personal",
      duration: "February 2018 - April 2018",
      link: "https://github.com/Sunil1234267",
    },
  ],
  
  achievements: [
    {
      title: "Committee Head - Aaruush Techno-Management Fest",
      organization: "SRM Institute of Science and Technology",
      duration: "December 2017 - September 2019",
      description: "Led organizing committee for one of India's largest techno-management festivals, managing workshops and events for diverse engineering departments. Coordinated activities for over 5,000 students, demonstrating leadership, problem-solving, and teamwork capabilities under high-pressure situations.",
    },
    {
      title: "Production Implementation - Feature Development",
      organization: "TVS Motors",
      duration: "March 2024 - January 2025",
      description: "Successfully led end-to-end development and production implementation of a critical 2-wheeler feature, from concept validation to market deployment, ensuring compliance with automotive standards and safety requirements.",
    },
    {
      title: "Team Leadership - EV Development",
      organization: "Pravaig Dynamics",
      duration: "December 2021 - December 2023",
      description: "Led a team of 2 engineers for complete electrification of existing ICE vehicle, managing software, electrical, and electronics integration while ensuring adherence to V-model lifecycle and SDLC methodologies.",
    },
  ],
  
  certifications: [
    {
      name: "Autosar Architecture",
      provider: "Udemy",
      category: "Automotive Software",
    },
    {
      name: "LabVIEW",
      provider: "Internshala",
      category: "Development Tools",
    },
    {
      name: "Ansys",
      provider: "Internshala",
      category: "Simulation & Analysis",
    },
    {
      name: "An Introduction to the Controller Area Network (CAN) Bus",
      provider: "Udemy",
      category: "Automotive Protocols",
    },
    {
      name: "Crash Course on Python",
      provider: "Google (Coursera)",
      category: "Programming Languages",
    },
    {
      name: "FPGA Development",
      provider: "LinkedIn Learning",
      category: "Hardware Development",
    },
    {
      name: "Internet of Things and Embedded Systems",
      provider: "Coursera",
      category: "IoT & Embedded",
    },
    {
      name: "MATLAB",
      provider: "LinkedIn Learning",
      category: "Development Tools",
    },
    {
      name: "Industrial Automation",
      provider: "LinkedIn Learning",
      category: "Automation",
    },
    {
      name: "Fundamentals of Project Planning and Management",
      provider: "Coursera",
      category: "Project Management",
    },
    {
      name: "Business Intelligence",
      provider: "Aaruush, SRM University",
      category: "Data Analysis",
    },
    {
      name: "Program Designing",
      provider: "KJP Automation",
      category: "Programming",
    },
    {
      name: "HackTrack",
      provider: "Aaruush, SRM University",
      category: "Technical Competition",
    },
  ],
  
  coCurricularActivities: [
    {
      title: "Committee Head, Aaruush Techno-Management Fest",
      description: "As a key organizer for one of India's largest techno-management fests, I managed workshops and events for diverse engineering departments. This high-pressure role involved coordinating activities for over 5,000 students, demanding continuous brainstorming, on-the-spot problem-solving, and effective teamwork to ensure the event's success.",
      duration: "December 2017 - September 2019",
    },
  ],
  
  volunteering: [
    {
      title: "Corporate Strategy and Implementation (CSI) Volunteer",
      organization: "Aaruush, SRM University",
      duration: "July 2017 - December 2017",
      description: "Contributed to social service initiatives for one of India's largest techno-management fests. My role involved strategic planning and implementation of outreach programs, requiring adaptability and quick problem-solving to engage with the community and ensure the success of our social campaigns.",
    },
  ],
};

export const navLinks = [
  { href: "/", label: "Home", icon: Home },
  { href: "/about", label: "About", icon: User },
  { href: "/experience", label: "Experience", icon: Briefcase },
  { href: "/projects", label: "Projects", icon: Book },
  { href: "/other", label: "Other", icon: GraduationCap }, // Renamed from Education
  { href: "/contact", label: "Contact", icon: Mail },
];

export const iconMap = {
  role: Briefcase,
  company: Building,
  duration: Home,
  responsibilities: HeartHandshake,
  degree: GraduationCap,
  institution: Building,
  certification: Award,
  location: MapPin,
  phone: Phone,
  email: Mail,
  linkedin: Linkedin,
  github: Github,
  internship: Lightbulb,
  coCurricular: Sparkles,
  volunteering: HeartHandshake,
};
